name: Acquire activation file

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file ğŸ”‘
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        continue-on-error: true
        uses: ./

      - name: Check for failure
        run: |
          if [ "${{ steps.getManualLicenseFile.outcome }}" != "failure"  ]; then
            echo "Expected failure, got ${{ steps.getManualLicenseFile.outcome }}"
            exit 1
          fi
      # Request manual activation file
      
      - name: Unity - Request Activation File
        id: requestActivationFile
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
      - name: Upload activation file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.requestActivationFile.outputs.filePath }}
          path: ${{ steps.requestActivationFile.outputs.filePath }}
          retention-days: 3

      - name: Set up Unity
        uses: actions/cache@v1.1.0
        with:
          unity-version: 2022.3.7f1  # ì‚¬ìš©í•  Unity ë²„ì „
          
     # NUnit Console ì„¤ì¹˜ ë° PATH ì„¤ì •
      - name: Install NUnit Console and add to PATH
        run: |
          # NUnit Console NuGet íŒ¨í‚¤ì§€ë¥¼ ê¸€ë¡œë²Œ ë„êµ¬ë¡œ ì„¤ì¹˜
          dotnet tool install --global NUnit.ConsoleRunner --version 3.12.0
          # ì„¤ì¹˜ëœ ë„êµ¬ì˜ ê¸°ë³¸ ê²½ë¡œë¥¼ PATHì— ì¶”ê°€
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # ìœ ë‹› í…ŒìŠ¤íŠ¸ ì‹¤í–‰
      - name: Run Unit Tests
        run: |
          # ì´ì œ nunit3-console ëª…ë ¹ì„ ì§ì ‘ ì‚¬ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
          nunit3-console Library/ScriptAssemblies/Tests.dll
